frontend-aviral-Mern:
  replicaCount: 2
  image:
    name: aviral/samplemicroservice-frontend
    repository: 975050024946.dkr.ecr.ca-central-1.amazonaws.com
    tag: latest
    port: 3000
  service:
    type: LoadBalancer
    port: 80

profileservice-be:
  replicaCount: 2
  image:
    name: aviral/samplemicroservice-profileservice
    repository: 975050024946.dkr.ecr.ca-central-1.amazonaws.com
    tag: latest
    port: 3002
  service:
    type: LoadBalancer
    port: 80

helloservice-be:
  replicaCount: 2
  image:
    name: aviral/samplemicroservice-helloservice
    repository: 975050024946.dkr.ecr.ca-central-1.amazonaws.com
    tag: latest
    port: 3001
  service:
    type: LoadBalancer
    port: 80
